### PR TITLE
fix: mount directory so it works on windows

### PR DESCRIPTION
**Pull request by jon-hagg**
### Purpose
Fix the mount so it works on windows and update readme accordingly. 

### Time to review
3 min

### CODE REVIEW

**Comment by rouille** [comment]
So we just require to have the license in the **plug/gurobi_license/** folder in place of **plug/** and it fixes the problem on Windows?

**Comment by jon-hagg** [comment]
> So we just require to have the license in the **plug/gurobi_license/** folder in place of **plug/** and it fixes the problem on Windows?

Yeah the issue I forgot is windows doesn't work with single file volume mounts - it has to be a directory. This doesn't fix the issue with academic licenses, but think we would still need this.

**Comment by rouille** [comment]
Do you want to convert it to a PR and merge it?

**Comment by jon-hagg** [comment]
> Do you want to convert it to a PR and merge it?

Yeah, I suppose, no point in waiting since it's been tested.

**Review by rouille — APPROVED** [review]

**Pull request merged**
